In [1]:
data_list=[1,2,3]

In [2]:
data_list

[1, 2, 3]

In [1]:
import numpy as np

In [4]:
arr=np.array(data_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
data_list2=[[10,20,30],[40,50,60],[70,80,90]]

In [7]:
arr2=np.array(data_list2)

In [8]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [11]:
arr3=np.array([1,2,3,4,5])#özellikle bir array olusturmamıza gerek yok.Dırekt np.array ın içine de yazabılırız. 

In [12]:
arr3

array([1, 2, 3, 4, 5])

In [13]:
arr3[0]

1

In [14]:
arr3[4]

5

In [16]:
arr2[2,2]#normal listelerden farklı.

90

In [17]:
arr2[5,5]#boyle bır ındeks olmadıgı ıcın hata verdi.

IndexError: index 5 is out of bounds for axis 0 with size 3

In [18]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(10,100,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [21]:
np.zeros(10)#zeros fonku sayesınde içine yazdıgımız mıktar kadar sıfırı liste şeklinde yazdırıyor.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(5)# nokta olmasının nedeni numpy integer degerlerımızı float şeklinde depoluyor.

array([1., 1., 1., 1., 1.])

In [24]:
np.zeros((2,2))# 2ye 2lik bir matris olusturup 0ları ona gore koydu.

array([[0., 0.],
       [0., 0.]])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.linspace(0,100,5)#0dan baslayıp 100e kadar git ve 5 eşit parçaya bölerek bu işlemi yap demektir.

array([  0.,  25.,  50.,  75., 100.])

In [29]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [30]:
np.eye(6)#eye fonksiyonu birim matris oluşturmamızı sağlıyor.İçine yazdıgımız sayı da kaca kaclık bır matrıs olması gerektııgını soyluyor.

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [32]:
np.random.randint(0,15)#0 15 arasında random deger donuyor.

4

In [34]:
np.random.randint(10)

0

In [37]:
np.random.randint(1,10,5)#1 ile 10 arasında random değer dondurup 5li matris yap demek.

array([2, 9, 4, 3, 9])

In [38]:
np.random.randint(1,10,(5,5))

array([[8, 1, 3, 1, 9],
       [7, 9, 4, 9, 2],
       [1, 2, 1, 8, 3],
       [5, 4, 5, 8, 1],
       [9, 4, 6, 3, 4]])

In [41]:
np.random.rand(5)#burda da 0 ile 1 arasında random sayı seçip 5li array yap dedik.

array([0.9252352 , 0.1467713 , 0.67328886, 0.33964637, 0.14046849])

In [44]:
np.random.randn(5)#0ın etrafında gaussian dağılımı yapıyor.

array([-1.81802168, -0.37454719, -0.1535491 ,  1.06908702,  0.65480288])

In [45]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.reshape(5,5)#5e5 lik bir matris olusturup bu degerleri girdi.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.reshape(6,6)#eğer listedeki bütün değerler eşleşmesse hata verir.

ValueError: cannot reshape array of size 25 into shape (6,6)

In [49]:
newArray=np.random.randint(1,100,10)
newArray

array([48, 96, 73, 27, 66,  2, 38, 61, 79, 24])

In [50]:
newArray.max()

96

In [51]:
newArray.min()

2

In [52]:
newArray.sum()

514

In [53]:
newArray.mean()#arraydeki sayıların ortalaması.

51.4

In [55]:
newArray.argmax()#arraydaki en buyuk sayının indeksini verdi.

1

In [56]:
newArray.argmin()

5

In [73]:
detarray=np.random.randint(1,100,25)

In [74]:
detarray

array([64,  2, 99, 32, 29, 10, 63, 80, 68, 35, 21, 64, 43, 72, 77, 58, 52,
       75, 79, 81, 29, 90, 21, 74,  4])

In [80]:
detarray=detarray.reshape(5,5)
detarray

array([[64,  2, 99, 32, 29],
       [10, 63, 80, 68, 35],
       [21, 64, 43, 72, 77],
       [58, 52, 75, 79, 81],
       [29, 90, 21, 74,  4]])

In [81]:
np.linalg.det(detarray)

141738890.99999967

In [86]:
detarray2=np.array([[1,2],[3,4]])
detarray2

array([[1, 2],
       [3, 4]])

In [87]:
np.linalg.det(detarray2)

-2.0000000000000004

In [89]:
round(np.linalg.det(detarray2))#daha güzel bir şekilde gostermıs oluyoruz.

-2

In [3]:
a=np.array([0,1,2])#meshgrid var olan arraylerdekı elemanları tek tek eşlememizi saglıyor.
b=np.array([7,8,9])
np.meshgrid(a,b)

[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])]