In [5]:
import numpy as np

In [6]:
arr=np.arange(1,10)

In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[1:5]

array([2, 3, 4, 5])

In [9]:
arr[:4]

array([1, 2, 3, 4])

In [10]:
arr[::2]

array([1, 3, 5, 7, 9])

In [11]:
arr[:3]=25# bunu yaparak 0 dan 3. indekse kadarkı butun degerler 25 olmus olucak.

In [12]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [13]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2=arr
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr2[0:3]=100
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [16]:
arr#bellekte aynı yerleri tuttukları için ikisi de değişmiş oldu.

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [17]:
arr=np.arange(1,10)

In [18]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2=arr.copy()#boylece bellekte farklı yerlerı tutmus olucaklar.

In [20]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr2[:3]=100

In [22]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [23]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
newArray=np.arange(1,21)

In [25]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
newArray=newArray.reshape(5,4)
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [27]:
newArray[0,0]

1

In [28]:
newArray[:,:2]#ilk iki sutunları al dedık.

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [30]:
newArray[:3,:3]#ilk 3 sütün ve satırı al dedik.

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [34]:
newArray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr>3#arr içindeki değerlere baktı ve 3 den küçük olanları false döndürdü.

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [39]:
booleanArray=arr>3

In [41]:
arr[booleanArray]#Bunun sayesinde filtreleme yapmış olduk.

array([ 4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])